### ISSUE TITLE
No identity option when instance has no access to metadata url

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/gcemetadata#2]
When an instance does not have access to a metadata url (such as when permissions are not provided to the service account):

http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/

gcemetadata fails with a cryptic error message.

```
> /usr/bin/gcemetadata --query instance --identity http://smt-gce.susecloud.net --identity-format full --xml
--identity-format possible values: "['full', 'standard']"
```

The 403 error is ignored when attempting to open the url https://github.com/SUSE-Enceladus/gcemetadata/blob/master/lib/gcemetadata/gcemetadata.py#L164.

This prevents `--identity` from being added as a valid command line option. When parsing the supplied `--identity` it is confused for `--identity-format` which leads to the error.

Ideally, if a metadata URL is inaccessible gcemetadata would at least log a warning. And it would be able to handle invalid commands. E.g. a possible example:

```
> /usr/bin/gcemetadata --query instance --identity http://smt-gce.susecloud.net --identity-format full --xml
Warning: unable to retrieve http://metadata.google.internal/computeMetadata/v1/instance/guest-attributes/
--identity is not a valid option
```

**Comment by rjschwei** [comment]
Fixed
